# Generated by Django 5.2.3 on 2025-06-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("blocked_users", "Может блокировать пользователей"),
                    ("view_all_users", "Может просматривать всех пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
