# Generated by Django 5.2.3 on 2025-06-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "datetime_start",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату и время первой отправки",
                        null=True,
                        verbose_name="Дата и время первой отправки",
                    ),
                ),
                (
                    "datetime_end",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату и время окончания отправки",
                        null=True,
                        verbose_name="Дата и время окончания отправки",
                    ),
                ),
                (
                    "status_mailing",
                    models.CharField(
                        choices=[("completed", "Завершена"), ("created", "Создана"), ("launched", "Запущена")],
                        default="created",
                        max_length=9,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "datetime_attempt",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату и время попытки",
                        null=True,
                        verbose_name="Дата и время попытки",
                    ),
                ),
                (
                    "status_attempt",
                    models.CharField(
                        choices=[("successfully", "Успешно"), ("unsuccessfully", "Не успешно")],
                        default="successfully",
                        max_length=14,
                        verbose_name="Статус попытки рассылки",
                    ),
                ),
                (
                    "response_mail_server",
                    models.TextField(
                        blank=True,
                        help_text="Введите ответ почтового сервера",
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "subject",
                    models.CharField(help_text="Введите тему письма", max_length=100, verbose_name="Тема письма"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, help_text="Введите текст письма", null=True, verbose_name="Тело письма"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recipient_email",
                    models.EmailField(help_text="Введите email", max_length=254, unique=True, verbose_name="Email"),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, help_text="Введите Ф.И.О.", max_length=250, null=True, verbose_name="Ф.И.О."
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="Введите комментарий", null=True, verbose_name="Комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
