# Generated by Django 5.2.3 on 2025-06-27 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mailings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="owner_mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_mailing",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец рассылки",
            ),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="mailing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailing",
                to="mailings.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AddField(
            model_name="mailingattempt",
            name="owner_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_attempt",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец попытки рассылки",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="owner_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец сообщения",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message",
                to="mailings.message",
                verbose_name="Сообщение",
            ),
        ),
        migrations.AddField(
            model_name="recipient",
            name="owner_recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_recipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец получателя сообщения",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="recipient",
            field=models.ManyToManyField(
                related_name="recipients", to="mailings.recipient", verbose_name="Получатели"
            ),
        ),
    ]
