# Generated by Django 5.2.3 on 2025-06-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_mailingattempt_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("blocked_mailing", "Может блокировать рассылки"),
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("view_all_recipients", "Может просматривать всех получателей"),
                    ("view_all_messages", "Может просматривать все сообщения"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status_mailing",
            field=models.CharField(
                choices=[
                    ("completed", "Завершена"),
                    ("created", "Создана"),
                    ("launched", "Запущена"),
                    ("blocked", "Отключена"),
                ],
                default="created",
                max_length=9,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
