# Generated by Django 5.2.3 on 2025-06-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_mailing_options_alter_mailing_status_mailing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("block_mailing", "Может блокировать рассылки"),
                    ("view_all_mailings", "Может просматривать все рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
